### ISSUE TITLE
Dev docs for Skycoin transactions

### ISSUE THREAD

**Issue by olemis** [skycoin/docs#12]
File : _data/devdocs//en/guides/transactions.md

- [x] Transactions overview (inputs , outputs, spending, internal details)
- [x] UTXO and P2PKH process and validation
- [x] No support for P2SH
- [x] Multisig ?
- [x] Standard vs non-standard tx
- [x] Signature hashes
- [x] Locktime And Sequence Number
- [x] Transaction Fees And Change
- [x] Key Reuse
- [x] Transaction Malleability

**Comment by olemis** [comment]
Cc @stdevEdu

**Comment by stdevEdu** [comment]
Issue solved
Cc @olemis

**Comment by olemis** [comment]
@stdevEdu I'll need PR from you after you apply updates to be consistent with #24 .

**Comment by olemis** [comment]
@stdevEdu I merged your PR #25 but this does not complete the work needed to close this issue . I have edited issue description with sub-tasks to make the goals clear .

**Comment by stdevEdu** [comment]
@olemis, all tasks have been completed.
I'll add a few more tasks to close the issue:

- [x] Add PTPKH reference
- [x] Add PTSH reference
- [x] Add standand transaction reference
- [x] Add transaction locktime reference
- [x] Add secp256k1 signature reference
- [x] Add reference links to file

**Comment by stdevEdu** [comment]
Issue finished. Opening PR.
