### ISSUE TITLE
Initial (dev) docs for Skycoin core

### ISSUE THREAD

**Issue by olemis** [skycoin/docs#2]
Add initial version of Skycoin dev guide, dev reference, and examples .

It'd be interesting to be able to follow  [bitcoin.org](https://github.com/bitcoin-dot-org/bitcoin.org) repository structure.

**Comment by ljesparis** [comment]
hello @olemis 
i need to add technical content about skycoin, should i add it to _data/devdocs/en/guides ? .. 
im following [bitcoin.org](https://github.com/bitcoin-dot-org/bitcoin.org) data structure

**Comment by olemis** [comment]
I was thinking of following the same conventions so that documentation workflow be easier. In the long term I propose to have at least `guide`, `examples`, and `reference` under `_data/devdocs/en` .

Nevertheless , @gz-c had a plan , so things can be different in the end .

p.s. this issue is related to #3 , BTW

**Comment by ljesparis** [comment]
where will be posted those desicions? any idea? i've got the task to upload technical content following .md hugo format...

**Comment by olemis** [comment]
This ticket will cover work on the intro , blockchain and P2P docs for the developers guide .
