### ISSUE TITLE
"How to recover the Skycoin wallet" pdf link

### ISSUE THREAD

**Issue by gz-c** [skycoin/docs#27]
Add this to a "links" page in user-guides,

also can convert it to a .md format for the website

[how to recover the Skycoin wallet step by step-eng.pdf](https://github.com/skycoin/docs/files/1637471/how.to.recover.the.Skycoin.wallet.step.by.step-eng.pdf)

**Comment by ljesparis** [comment]
@gz-c how is that about "links" page?
a common .md file with all kind of guide links?

**Comment by gz-c** [comment]
@ljesparis yes for now, until its organized better

We could rewrite these pdfs as .md instructions too

**Comment by ljesparis** [comment]
@gz-c also pdfs and txt from #5, right?

**Comment by ljesparis** [comment]
check following changes:
* [how to recover skycoin wallet](https://github.com/skycoin/docs/blob/pdfs/user-guides/leonardo/wallets/how%20to%20recover%20a%20skycoin%20wallet.md)
* [how to install skycoin wallet](https://github.com/skycoin/docs/blob/pdfs/user-guides/leonardo/wallets/How%20to%20install%20skycoin%20wallet.md)
* [How to secure your skycoin wallet](https://github.com/skycoin/docs/blob/pdfs/user-guides/leonardo/wallets/How%20to%20secure%20your%20skycoin%20wallet.md)
* [How to purchase skycoin](https://github.com/skycoin/docs/blob/pdfs/user-guides/leonardo/skycoin/How%20to%20purchase%20Skycoin.md)
* [link page](https://github.com/skycoin/docs/blob/pdfs/user-guides/links.md)

**Comment by gz-c** [comment]
@ljesparis looks good, we can remove the pdf links page if you've converted them to md files

**Comment by gz-c** [comment]
@ljesparis add the video instructions

How to Secure Skycoin Wallet
https://www.youtube.com/watch?v=lXoXCBUkUO0&feature=youtu.be

to "how to secure your skycoin wallet"

**Comment by ljesparis** [comment]
@gz-c check [how to secure skycoin wallet](https://github.com/skycoin/docs/blob/pdfs/user-guides/leonardo/wallets/How%20to%20secure%20your%20skycoin%20wallet.md)
