### ISSUE TITLE
Command line tool to extract & synch doc references

### ISSUE THREAD

**Issue by olemis** [skycoin/docs#3]
Synchronize Bitcoin.org -> Skycoin.net doc link references

Skycoin docs structure is inspired on Bitcoin.org structure.
Both are crypto currency systems powered by block chains.
Therefore there are a lot of intersections. Similarities are
particularly evident in the glossary of terms, but not limited
to that.

This should be a script implementing the following workflow:

- Recursively parse .md files in _data/ and its subfolders
   looking for link references
- If the reference is already included in _includes/references.md
   then continue ...
- ... else if the reference exists in Bitcoin.org docs then
    import it from there and tag it as TODO: REVIEW
- ... else create a new entry in _includes/references.md
    and tag it as TODO: EMPTY

This is necessary to limit references to the scope of Skycoin
boundaries , keep docs in sync , and discover dangling references
in the documentation.

Cc @stdevjorge

**Comment by m4yk3ldev** [comment]
I added docstrings for the command line tool . @olemis could you please check this ? It's based on what we discussed but I might be missing something .

**Comment by olemis** [comment]
@stdevLeonel thanks . @stdevjorge please fetch recent changes in [stdevLeonel_t3_doclinks](https://github.com/simelo/skycoin-dev/tree/stdevLeonel_t3_doclinks) and continue from there (only docstrings added) .

p.s. @stdevLeonel @stdevDcmorales @stdevjorge @stdevOsmel notice above the reference to 
changeset 466da60 due to including `refs #3` in commit message . Please use that style  consistently as often as you can .

**Comment by olemis** [comment]
oh ! ... I forgot @stdevjorge doc references are like this `[ref][text]` e.g. `[pre-compiled executable][core executable]` .

**Comment by olemis** [comment]
Done !
