### ISSUE TITLE
Setup initial dev.skycoin.net site

### ISSUE THREAD

**Issue by rngadam** [skycoin/docs#4]
Based on https://bitcoin.org/en/developer-documentation as a model, want to create dev.skycoin.net

* [ ] create a very simple Hugo base site with a top-level structure
  * Guides
  * References
  * Examples
  * Glossary
* [ ] deploy to s3 using Travis (see blog/.travis.yml)
* [ ] create developer site specific theme
  * must be part of the repo and audited to prevent 3rd party code insertion
* [ ] turn style from blog to searchable documentation
  *  add generated static search dialog (https://github.com/blevesearch/hugoidx)

**Comment by rngadam** [comment]
there's already a Hugo theme for Skycoin here: 

https://github.com/skycoin/blog/tree/master/themes/skycoin

probably want to take this to its own repository ```gohugo-theme-skycoin```  and use:

```
git submodule add https://github.com/skycoin/gohugo-theme-skycoin.git themes/skycoin
```

**Comment by rngadam** [comment]
after discussions, visual presentation and site needs to be fully self-encapsulated.

**Comment by rngadam** [comment]
a nice example of a documentation specific theme: https://themes.gohugo.io/docdock/

**Comment by olemis** [comment]
Any progress on Hugo setup? I'd like to avoid duplicate work if somebody already started doing so .

These are further instructions mentioned by @gz-c 

"We will need a build script for the entire repo to output to a build folder, then i will have travis autodeploy it . We intend to use hugo for the other parts, i will leave this be as python script for now"
