### ISSUE TITLE
Create document explaining coin hours

### ISSUE THREAD

**Issue by gz-c** [skycoin/docs#75]
Coin hours are earned at a rate of 1/3600 coinhours per second.  Fractional coinhours are not allowed and are always rounded down.

This leads to the following cases:

* 0.1 coins earns 1 coinhour per 10 hours
* 1 coin earns 1 coinhour per hour
* 3600 coins earn 1 coinhour per second

Coinhours are updated when a new block comes in.  The head block time dictates the clock time.  If there is no transaction activity, coinhours will not be updated.

**Comment by olemis** [comment]
Something has been written about [coin hours in docs](https://github.com/skycoin/docs/blob/master/_data/dev-docs/guides/transactions.md#coin-hours)

**Comment by olemis** [comment]
@stdevEdu could you please add what is missing in that .md doc ?
Thnx in advance

**Comment by gz-c** [comment]
Coin hours needs its own document

**Comment by stdevEdu** [comment]
@gz-c, should I base the document fully on the contents of the skycoin code, or rather use external info?

**Comment by olemis** [comment]
@gz-c is this users docs or dev docs ?

@stdevEdu if this was for dev docs I'd rather say both sources would be ok and , in the case of clashes , source code prevails . @gz-c cmmiw

**Comment by stdevEdu** [comment]
Roger that

2018-03-11 23:26 GMT-04:00 Olemis Lang <notifications@github.com>:

**Comment by gz-c** [comment]
It should be mostly a description of how it works.  The target audience is 3rd party developers and advanced users that wish to understand the details of the coin hours mechanism.

**Comment by olemis** [comment]
I guess the best location for it is dev docs examples .

**Comment by gz-c** [comment]
example of what? it is a core feature / property of skycoin

**Comment by gz-c** [comment]
we get nonstop questions of "how do coinhours work?" from the community. don't hide it in dev examples.

**Comment by stdevEdu** [comment]
First approach finished. PR #76

**Comment by olemis** [comment]
@gz-c there are three dev-docs folders : references , guides , and examples . What I meant before was that this looks like a good match for dev docs examples folder , since this would not be a reference , nor a guide , but an explanation of how something works based on an example . 

Nonetheless , if another location is better just let us know .

**Comment by olemis** [comment]
Well , now that I see @stdevEdu included it in guides . No big deal afaict

**Comment by stdevEdu** [comment]
@gz-c and @olemis, I have two questions that I included as comments in the doc:

Q: Can Coin Hours play a role with CX/CXO analogous to ETH's gas with EVM?

Q: Some consulted materials say that each transaction will burn 50% of the accumulated Coin Hours in spent UXTX, but I can't find support for that in the code. Following @olemis' guideline, I give priority to the code. Is that correct?

**Comment by stdevEdu** [comment]
Other than those remarks, the doc is fairly ready at PR #76

**Comment by gz-c** [comment]
I merged it and will finish the document

**Comment by gz-c** [comment]
Here is an article written by someone else about coinhours, it is focused on a general audience but covers the basics well: https://christianott.co/skycoin_coinhours_en/
