### ISSUE TITLE
Possible typo reference to BitCoin instead of Skycoin in p2p_network.md

### ISSUE THREAD

**Issue by BigOokie** [skycoin/docs#79]
Just reading through the docs. Looks like a possible typo reference to Bitcoin instead of Skycoin in the p2p_network.md document

Extract of specific section below

“As a manual fallback option, **Bitcoin** Core also provides several command-line connection options. See the -help text for details. Other Skycoin client software should be programmed to do the same thing.”

Should read “Skycoin Core...” in that first sentence I think.

**Comment by BigOokie** [comment]
This is the file
https://github.com/skycoin/docs/blob/master/_data/dev-docs/guides/p2p_network.md

**Comment by stdevEdu** [comment]
This should be it.
