### ISSUE TITLE
Document INTR upgrade in v24 , v25 , v26

### ISSUE THREAD

**Issue by olemis** [skycoin/docs#91]
explained and implemented in skycoin/skycoin#1517 skycoin/skycoin#1517 skycoin/skycoin#1518 skycoin/skycoin#1519

**Comment by gz-c** [comment]
Maybe we should move these kinds of docs to the skycoin/skycoin wiki...

**Comment by olemis** [comment]
This is for the [P2P reference docs](https://www.skycoin.net/docs/dev-docs/references/p2p_networking/) .

**Comment by gz-c** [comment]
It's transitory, I don't think it belongs there, the INTR upgrade is a set of steps for us to follow, in the end the docs will be updated with the new packet

**Comment by gz-c** [comment]
The docs published to the site are mainly for outsiders

**Comment by stdevEdu** [comment]
@olemis, @gz-c, please, close this issue, as the three branches have already been merged

**Comment by olemis** [comment]
Really ? These changes were meant to be merged before each release . I'll take a look .

**Comment by olemis** [comment]
@stdevEdu u should have included `fixes #91` in last PR title

**Comment by olemis** [comment]
@stdevEdu I'll keep this issue open for you to fix the following 👍 

- [x] Correct genesis hash in `v25` example of `INTR` message .

**Comment by stdevEdu** [comment]
Finished. PR #97 & #98.
